name: 'Update website'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.x

        - name: Run unit tests
          run: dotnet test

        - name: Generate website
          run: dotnet publish portfolio/myportfolio.csproj --configuration Release --output build

        - name: Fix base tag
          run: sed -i 's/<base href="\/" \/>/<base href="\/portfolio\/" \/>/g' build/wwwroot/index.html

        - name: Fix 404 page
          run: cp build/wwwroot/index.html build/wwwroot/404.html
          
        - name: Fix Jekyll conflict
          run: touch build/wwwroot/.nojekyll

        - name: Publish website
          if: ${{ github.ref == 'refs/heads/main' }}
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BASE_BRANCH: main
            BRANCH: gh-pages
            FOLDER: build/wwwroot
            SINGLE_COMMIT: true
